#!/usr/bin/env python3
"""Rebuild HQ's registry.yaml from the source declared in hq.yaml (ADR #6).

Sources:
  paths  (default) the `paths:` list in hq.yaml; id = absolute path; needs no other tool.
  orca             the projects added to Orca: `<orca_cli> repo list --json`, group names from
                   `<orca_cli> repo groups --json` (optional — without it names come from the
                   previous registry, else null); id = Orca repo id.

A page slug is fixed when a project first appears. A project leaves the registry only when a
*successful* read of the source no longer has it — then its page moves to projects/_archive/.
A source that cannot be read leaves registry.yaml untouched. An unchanged source rewrites
nothing. Stdlib only: hq.yaml and registry.yaml use a small YAML subset (scalars, lists of
scalars, lists of flat mappings; JSON-quoted strings).

Usage: python3 scripts/hq_registry.py [--hq DIR] [--dry-run]
Exit: 0 written or unchanged · 2 source not readable (registry kept) · 3 bad hq.yaml.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

HEADER = "# Generated by scripts/hq_registry.py from the source in hq.yaml (ADR #6). Do not edit by hand.\n"
FIELDS = ("id", "slug", "name", "path", "kind", "host", "group", "group_id")


class SourceError(Exception):
    pass


def _scalar(value):
    value = value.strip()
    if value == "":
        return None
    try:
        return json.loads(value)
    except ValueError:
        return value  # bare word, e.g. `source: paths`


def read_yaml_subset(path):
    """Top-level `key: value`, `key:` + `  - scalar` lists, `key:` + `  - k: v` / `    k: v` mappings."""
    data, key, item = {}, None, None
    if not os.path.exists(path):
        return data
    with open(path, encoding="utf-8") as f:
        for n, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            top = re.match(r"^([a-z_]+):\s?(.*)$", line)
            if top:
                key, item = top.group(1), None
                data[key] = _scalar(top.group(2))
                continue
            entry = re.match(r"^\s+- ([a-z_]+):\s?(.*)$", line)
            if entry and key:
                item = {entry.group(1): _scalar(entry.group(2))}
                data[key] = (data[key] or []) + [item]
                continue
            cont = re.match(r"^\s{4,}([a-z_]+):\s?(.*)$", line)
            if cont and item is not None:
                item[cont.group(1)] = _scalar(cont.group(2))
                continue
            listed = re.match(r"^\s+- (.+)$", line)
            if listed and key:
                data[key] = (data[key] or []) + [_scalar(listed.group(1))]
                item = None
                continue
            raise ValueError(f"{path}:{n}: unreadable line: {line!r}")
    return data


def render_registry(source, entries):
    out = [HEADER, f"source: {json.dumps(source)}\n", "projects:\n"]
    for e in entries:
        for i, key in enumerate(FIELDS):
            out.append(f"{'  - ' if i == 0 else '    '}{key}: {json.dumps(e[key], ensure_ascii=False)}\n")
    return "".join(out)


def call_orca(cli, *args):
    try:
        proc = subprocess.run([cli, *args, "--json"], capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise SourceError(f"`{cli} {' '.join(args)}` could not run: {exc}") from exc
    try:
        envelope = json.loads(proc.stdout)
    except ValueError as exc:
        raise SourceError(f"`{cli} {' '.join(args)}` exit {proc.returncode}, no JSON: "
                          f"{(proc.stderr or proc.stdout).strip()[:300]}") from exc
    if proc.returncode != 0 or not envelope.get("ok"):
        message = (envelope.get("error") or {}).get("message", "") or proc.stderr.strip()
        raise SourceError(f"`{cli} {' '.join(args)}` failed: {message[:300]}")
    return envelope["result"]


def read_orca(config, previous, warnings):
    cli = config.get("orca_cli") or "orca"
    repos = call_orca(cli, "repo", "list")["repos"]
    try:
        names = {g["id"]: g["name"] for g in call_orca(cli, "repo", "groups")["groups"]}
    except SourceError as exc:
        names = {e["group_id"]: e["group"] for e in previous if e.get("group_id")}
        warnings.append(f"group names unavailable ({exc}); kept the previous ones")
    found = []
    for r in repos:
        host = r.get("executionHostId") or (f"ssh:{r['connectionId']}" if r.get("connectionId") else "local")
        group_id = r.get("projectGroupId")
        found.append({
            "id": r["id"], "name": r.get("displayName") or os.path.basename(r["path"]),
            "path": r["path"], "kind": r.get("kind") or "git", "host": host,
            "group": names.get(group_id) if group_id else None, "group_id": group_id,
            "order": (r.get("addedAt") or 0, r["id"]),
        })
    return found


def read_paths(config, warnings):
    found = []
    for i, raw in enumerate(config.get("paths") or []):
        path = os.path.abspath(os.path.expanduser(str(raw)))
        if not os.path.isdir(path):
            warnings.append(f"{path} is not a directory right now; listed anyway")
        found.append({
            "id": path, "name": os.path.basename(path.rstrip(os.sep)) or path, "path": path,
            "kind": "git" if os.path.exists(os.path.join(path, ".git")) else "folder",
            "host": "local", "group": None, "group_id": None, "order": (i, path),
        })
    return found


def slugify(name):
    return re.sub(r"[^a-z0-9_-]+", "-", name.lower()).strip("-") or "project"


def build(hq, found, previous):
    hq_real = os.path.realpath(hq)
    by_id = {e["id"]: e for e in previous}
    taken = {e["slug"] for e in previous}
    entries, seen = [], set()
    for f in sorted(found, key=lambda x: x["order"]):
        if os.path.realpath(f["path"]) == hq_real or f["id"] in seen:
            continue
        seen.add(f["id"])
        old = by_id.get(f["id"])
        if old:
            slug = old["slug"]
        else:
            base = slug = slugify(f["name"])
            n = 2
            while slug in taken:
                slug, n = f"{base}-{n}", n + 1
            taken.add(slug)
        entries.append({**{k: f[k] for k in FIELDS if k in f}, "slug": slug})
    entries.sort(key=lambda e: e["slug"])
    removed = [e for e in previous if e["id"] not in seen]
    return entries, removed


def archive_pages(hq, removed, dry_run):
    moved = []
    for e in removed:
        page = os.path.join(hq, "projects", f"{e['slug']}.md")
        if os.path.exists(page):
            moved.append(e["slug"])
            if not dry_run:
                os.makedirs(os.path.join(hq, "projects", "_archive"), exist_ok=True)
                shutil.move(page, os.path.join(hq, "projects", "_archive", f"{e['slug']}.md"))
    return moved


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--hq", default=".", help="HQ root (default: cwd)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    hq = os.path.abspath(args.hq)
    registry = os.path.join(hq, "registry.yaml")
    try:
        config = read_yaml_subset(os.path.join(hq, "hq.yaml"))
        previous = read_yaml_subset(registry).get("projects") or []
    except ValueError as exc:
        print(f"hq_registry: {exc}", file=sys.stderr)
        return 3
    source = config.get("source") or "paths"
    warnings = []
    try:
        if source == "orca":
            found = read_orca(config, previous, warnings)
        elif source == "paths":
            found = read_paths(config, warnings)
        else:
            print(f"hq_registry: unknown source {source!r} in hq.yaml (paths | orca)", file=sys.stderr)
            return 3
    except (SourceError, KeyError, TypeError) as exc:
        print(f"hq_registry: source {source!r} not readable, registry.yaml kept as is — {exc}", file=sys.stderr)
        return 2

    entries, removed = build(hq, found, previous)
    text = render_registry(source, entries)
    old_text = open(registry, encoding="utf-8").read() if os.path.exists(registry) else None
    added = sorted({e["slug"] for e in entries} - {e["slug"] for e in previous})
    moved = archive_pages(hq, removed, args.dry_run)
    changed = text != old_text
    if changed and not args.dry_run:
        tmp = registry + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, registry)
    print(json.dumps({
        "source": source, "projects": len(entries), "added": added,
        "removed": sorted(e["slug"] for e in removed), "archived_pages": moved,
        "changed": changed, "dry_run": args.dry_run, "warnings": warnings,
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
