#!/usr/bin/env bash
# Strata A5 — PreToolUse guard: refuse a file write BEFORE it happens.
#
# The playbook line this implements: "a skill is an advisory control… a policy
# that must always hold needs something deterministic behind the skill". Two
# Strata rules were prose-only until now; this is their deterministic half.
#
# RULE (a) — raw/ is a mirror, never a source.
#   Any Edit/Write/MultiEdit whose file_path is under raw/ is refused. raw/ is
#   regenerated from docs/ by sync_raw_mirror.sh; a hand edit there is either
#   lost on the next mirror or, worse, diverges silently. Until now this was a
#   CLAUDE.md sentence plus a pre-commit check that fires AFTER the damage.
#   Escape: STRATA_ALLOW_RAW_EDIT=1 (for a deliberate one-off repair).
#
# RULE (b) — while fixing, tests are read-only.
#   While the toggle file .strata/guard-tests exists, writes to test files are
#   refused. An agent making a failing test pass must not be able to weaken the
#   test — that is the whole evidentiary value of TDD. feature/refactor create
#   the toggle at "make it pass" and remove it once green; SessionStart warns if
#   one is left behind. Escape: delete .strata/guard-tests.
#
# CONTRACT (Claude Code PreToolUse): payload JSON on stdin; exit 2 refuses the
# action and stderr is shown to the model as the reason; exit 0 allows.
# LOOP/FAIL-OPEN ORDER, same discipline as the Stop gate:
#   1. no payload / no file_path parseable   -> exit 0 (never guess)
#   2. not a write tool                       -> exit 0
#   3. rule (a), then rule (b)                -> exit 2 with a reason naming the escape
# PERFORMANCE: fires on every write, so grep/sed only — no python3 (~36 ms
# interpreter start measured for the Stop gate; unaffordable here).

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT" || exit 0

payload=""
if [ ! -t 0 ]; then payload="$(cat 2>/dev/null || true)"; fi
[ -n "$payload" ] || exit 0

tool="$(printf '%s' "$payload" \
  | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
case "$tool" in
  Edit|Write|MultiEdit|NotebookEdit) ;;
  *) exit 0 ;;
esac

file_path="$(printf '%s' "$payload" \
  | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
[ -n "$file_path" ] || exit 0

# Normalise to a repo-relative path. An absolute path may arrive through a
# symlinked prefix (macOS: /var → /private/var, while git reports the physical
# root), so resolve the directory part physically before stripping the root.
# If the directory does not exist yet, leave the path alone — fail open, never
# guess (the pre-commit raw-mirror check still catches that case later).
rel="$file_path"
case "$rel" in
  /*)
    dir="$(cd "$(dirname "$rel")" 2>/dev/null && pwd -P || true)"
    [ -n "$dir" ] && rel="$dir/$(basename "$rel")"
    rel="${rel#"$REPO_ROOT"/}"
    ;;
esac
rel="${rel#./}"

# --- rule (a): raw/ mirror ---------------------------------------------------
case "$rel" in
  raw/*)
    if [ "${STRATA_ALLOW_RAW_EDIT:-0}" != "1" ]; then
      echo "Strata guard: refusing to write ${rel} — raw/ is a mirror of docs/, regenerated by scripts/sync_raw_mirror.sh. Edit the source under docs/ instead. Deliberate one-off repair: STRATA_ALLOW_RAW_EDIT=1." >&2
      exit 2
    fi
    ;;
esac

# --- rule (b): tests are read-only while a fix is in progress -----------------
if [ -e .strata/guard-tests ]; then
  base="${rel##*/}"
  is_test=0
  case "$rel" in
    tests/*|test/*|*/tests/*|*/test/*|*/__tests__/*|spec/*|*/spec/*) is_test=1 ;;
  esac
  # `*_test.*` is the spec's pattern (D2) — it also covers Dart/Flutter, Deno, Ruby, Rust
  # conventions (foo_test.dart / .ts / .rb / .rs); the first cut narrowed it to .py/.go and
  # the diff review caught the gap in a fixture.
  case "$base" in
    test_*.py|*_test.*|*.test.*|*.spec.*|*_spec.rb|*Test.java|*Tests.cs) is_test=1 ;;
  esac
  if [ "$is_test" -eq 1 ]; then
    echo "Strata guard: refusing to write ${rel} — a fix is in progress (.strata/guard-tests is set), so test files are read-only. Fix the code, not the test. If the test itself is wrong, finish or abandon the fix first, then: rm .strata/guard-tests." >&2
    exit 2
  fi
fi

exit 0
